language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules

after_success:
  - git config --global user.name "thuhole"
  - git config --global user.email "thuhole@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://thuhole:${GH_TOKEN}@github.com/thuhole/webhole.git
  - CI=false REACT_APP_BUILD_INFO=$(printf "Stable%s" "$(TZ=Asia/Shanghai date +"%y%m%d%H%M%S")") npm run build
  #额，这里用了个骚操作来修复Service Worker在Precache CDN内容的时候index.html返回content-type text/plain的问题
  - sed -i 's/\/\/cdn.jsdelivr.net\/gh\/thuhole\/webhole@gh-pages-master\/index.html/.\/index.html/g' build/*-*
  - sed -i 's/\/\/cdn.jsdelivr.net\/gh\/thuhole\/webhole@gh-pages-master\/service-worker.js/.\/service-worker.js/g' build/*-*
  - sed -i 's/"\/\/cdn.jsdelivr.net\/gh\/thuhole\/webhole@gh-pages-master","\/service-worker.js"/".","\/service-worker.js"/' build/static/js/*.js
  - sed -i 's/storage.googleapis.com\/workbox-cdn\/releases\/4.3.1/cdn.jsdelivr.net\/npm\/workbox-cdn@4.3.1\/workbox/g' build/service-worker.js
  - npm run deploy
